all:
	make -C 1_Example
	make -C 2_Example
	make -C 3_Example
	make -C 4_Example
	make -C 5_Example -f test

clean:
	make -C 2_Example clean
	make -C 3_Example clean
	make -C 4_Example clean
	make -C 5_Example -f test clean

